apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart-mail.fullname" . }}-credential
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "stalwart-mail.labels" . | nindent 4 }}
data:
  admin-password: {{ .Values.admin.password | b64enc | quote }}
