apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart-mail.fullname" . }}
  labels:
    {{- include "stalwart-mail.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with $.Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  ports:
  {{- range $key, $val := $.Values.service.ports }}
    - name: {{ $key }}
      port: {{ $val }}
      targetPort: {{ $val }}
  {{- end }}
  selector:
    {{- include "stalwart-mail.selectorLabels" . | nindent 4 }}
---
{{- if .Values.externalAccess.enabled }}
{{- range $i := until (int .Values.replicaCount) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart-mail.fullname" $ }}-{{ $i }}
  labels:
    {{- include "stalwart-mail.labels" $ | nindent 4 }}
  {{- with $.Values.externalAccess.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.externalAccess.service.type }}
  {{- with $.Values.externalAccess.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  ports:
  {{- range $key, $val := $.Values.externalAccess.service.ports }}
    - name: {{ $key }}
      port: {{ $val }}
      targetPort: {{ $val }}
  {{- end }}
  selector:
    {{- include "stalwart-mail.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "stalwart-mail.fullname" $ }}-{{ $i }}
{{- end }}
{{- end }}
